# Generated by Django 6.0.2 on 2026-02-20 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ inválido. Use o formato XX.XXX.XXX/XXXX-XX.')], verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('resp_nttdata', models.CharField(max_length=255, verbose_name='responsável NTT Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cnpj'], name='clientes_cl_cnpj_db43af_idx')],
            },
        ),
    ]
