# Generated by Django 6.0.2 on 2026-02-20 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proj_ntt', models.CharField(max_length=255, verbose_name='nome do projeto (NTT)')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('qte_pessoas', models.IntegerField(default=0, verbose_name='quantidade prevista de pessoas')),
                ('qte_pessoas_atual', models.IntegerField(default=0, verbose_name='quantidade atual de pessoas')),
                ('contrato_pend', models.BooleanField(default=False, verbose_name='contrato pendente')),
                ('ov', models.CharField(blank=True, max_length=50, verbose_name='OV')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='contratos.contrato', verbose_name='contrato')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_gerenciados', to=settings.AUTH_USER_MODEL, verbose_name='gestor do projeto')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['nome_proj_ntt'],
            },
        ),
        migrations.CreateModel(
            name='GestorProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proj', models.CharField(max_length=255, verbose_name='nome do projeto')),
                ('nome_colaborador', models.CharField(blank=True, max_length=255, verbose_name='nome do colaborador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='cliente')),
                ('id_colaborador', models.ForeignKey(blank=True, help_text='Colaborador específico sob a gestão deste GP neste projeto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_gp', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
                ('id_gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestoes', to=settings.AUTH_USER_MODEL, verbose_name='gerente de projeto')),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores_projeto', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'gestor de projeto',
                'verbose_name_plural': 'gestores de projeto',
            },
        ),
        migrations.CreateModel(
            name='ColaboradorProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proj', models.CharField(max_length=255, verbose_name='nome do projeto')),
                ('ov_projeto', models.CharField(blank=True, max_length=50, verbose_name='OV do projeto')),
                ('nome_colaborador', models.CharField(blank=True, max_length=255, verbose_name='nome do colaborador')),
                ('centro_custo', models.CharField(blank=True, max_length=50, verbose_name='centro de custo')),
                ('custo_projeto', models.BooleanField(default=True, verbose_name='custo no projeto')),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='função')),
                ('dt_inicio', models.DateField(verbose_name='data de início')),
                ('dt_fim', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('squad', models.CharField(blank=True, max_length=100, verbose_name='squad')),
                ('contato_projeto', models.CharField(blank=True, max_length=255, verbose_name='contato do projeto')),
                ('resp_cliente', models.CharField(blank=True, max_length=255, verbose_name='responsável do cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_como_gestor', to=settings.AUTH_USER_MODEL, verbose_name='gestor')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='cliente')),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
                ('p01', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_p01', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner 1')),
                ('p02', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_p02', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner 2')),
                ('id_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'alocação de colaborador',
                'verbose_name_plural': 'alocações de colaboradores',
                'ordering': ['-dt_inicio'],
                'indexes': [models.Index(fields=['dt_inicio', 'dt_fim'], name='projetos_co_dt_inic_e554af_idx'), models.Index(fields=['id_colaborador'], name='projetos_co_id_cola_546559_idx')],
            },
        ),
    ]
