# Generated by Django 6.0.2 on 2026-02-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('fte', models.FloatField(default=0, verbose_name='FTE (Full-Time Equivalent)')),
                ('dt_inicio', models.DateField(verbose_name='data de início')),
                ('dt_fim', models.DateField(verbose_name='data de término')),
                ('renova', models.BooleanField(default=False, verbose_name='renovável')),
                ('ov_anterior', models.CharField(blank=True, max_length=50, verbose_name='OV anterior')),
                ('resp_cliente', models.CharField(blank=True, max_length=255, verbose_name='responsável do cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-dt_inicio'],
            },
        ),
    ]
