# Generated by Django 6.0.2 on 2026-02-20 19:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=255, verbose_name='nome completo')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='matrícula')),
                ('pos', models.CharField(blank=True, max_length=50, verbose_name='posição')),
                ('req', models.CharField(blank=True, max_length=50, verbose_name='requisição')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='função')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\(\\)\\-]{8,20}$', 'Telefone inválido.')], verbose_name='telefone')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='estado')),
                ('local_escritorio', models.CharField(blank=True, max_length=100, verbose_name='local do escritório')),
                ('dt_admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('dt_demissao', models.DateField(blank=True, null=True, verbose_name='data de demissão')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salário')),
                ('cod_gestor_sup', models.CharField(blank=True, max_length=50, verbose_name='cód. gestor superior')),
                ('cod_gestor', models.CharField(blank=True, max_length=50, verbose_name='cód. gestor')),
                ('nome_gestor', models.CharField(blank=True, max_length=255, verbose_name='nome do gestor')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('afastado', 'Afastado')], default='ativo', max_length=20, verbose_name='status')),
                ('role', models.CharField(choices=[('diretor', 'Diretor'), ('gestor', 'Gestor'), ('gerente_projeto', 'Gerente de Projeto'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='perfil')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='foto')),
                ('gestor_direto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL, verbose_name='gestor direto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['role'], name='colaborador_role_083a3b_idx'), models.Index(fields=['status'], name='colaborador_status_24a5fd_idx'), models.Index(fields=['matricula'], name='colaborador_matricu_d0ef70_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
