# Generated by Django 6.0.2 on 2026-02-20 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='número de série')),
                ('eh_ntt', models.BooleanField(default=False, verbose_name='é da NTT Data')),
                ('patrimonio_ntt', models.CharField(blank=True, max_length=50, null=True, verbose_name='patrimônio NTT')),
                ('eh_cliente', models.BooleanField(default=False, verbose_name='é do cliente')),
                ('patrimonio_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='patrimônio cliente')),
                ('localizacao', models.CharField(blank=True, max_length=255, verbose_name='localização')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'notebook',
                'verbose_name_plural': 'notebooks',
                'ordering': ['numero_serie'],
            },
        ),
    ]
